# -*- coding: utf-8 -*-
"""Hospital Inpatient Discharges Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ix7VxLH0IiEA3WOaoEDwloYCJn8C0cSY
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Hospital Inpatient Discharge Dashboard", layout="wide")

st.title("Hospital Inpatient Discharges Dashboard")

uploaded = st.file_uploader("/content/drive/MyDrive/Dataset Scenario 2:Hospital Inpatient Discharges Dashboard/Hospital_Inpatient_Discharges__SPARCS_De-Identified___2021_20231012.csv", type=["csv"])

if uploaded:
    df = pd.read_csv(uploaded)

    df = df.dropna(subset=["length_of_stay"])
    df = df[df["length_of_stay"] >= 0]

    if "total_charges" in df.columns:
        df["total_charges"] = df["total_charges"].astype(str).str.replace(",", "").astype(float)

    st.subheader("Dataset Preview")
    st.dataframe(df.head())

    st.subheader("Summary Statistics")
    c1, c2, c3 = st.columns(3)
    c1.metric("Total Patients", len(df))
    c2.metric("Average Length of Stay", round(df["length_of_stay"].mean(), 2))
    c3.metric("Average Charges", round(df["total_charges"].mean(), 2))

    st.header("Interactive Visualizations")

    st.subheader("1. Average Hospital Stay per Diagnosis Code")
    diag_stay = df.groupby("diagnosis_code")["length_of_stay"].mean().reset_index()
    fig1 = px.bar(diag_stay, x="diagnosis_code", y="length_of_stay")
    st.plotly_chart(fig1, use_container_width=True)

    st.subheader("2. Total Charges by Severity Level")
    if "severity" in df.columns:
        fig2 = px.box(df, x="severity", y="total_charges")
        st.plotly_chart(fig2, use_container_width=True)

    st.subheader("3. Heatmap: Avg. Stay Duration by Facility and County")
    if "facility" in df.columns and "county" in df.columns:
        heat = df.groupby(["facility", "county"])["length_of_stay"].mean().reset_index()
        fig3 = px.density_heatmap(heat, x="facility", y="county", z="length_of_stay")
        st.plotly_chart(fig3, use_container_width=True)

    st.subheader("4. Patient Distribution by Payment Type")
    if "payment_type" in df.columns:
        pay_count = df["payment_type"].value_counts().reset_index()
        fig4 = px.pie(pay_count, names="index", values="payment_type")
        st.plotly_chart(fig4, use_container_width=True)

    st.subheader("5. Distribution of Length of Stay")
    fig5 = px.histogram(df, x="length_of_stay")
    st.plotly_chart(fig5, use_container_width=True)
else:
    st.info("Upload a CSV file to begin.")