# -*- coding: utf-8 -*-
"""Hospital Inpatient Discharges Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ix7VxLH0IiEA3WOaoEDwloYCJn8C0cSY
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

st.set_page_config(page_title="Hospital Inpatient Discharges Dashboard", layout="wide")

st.title("Hospital Inpatient Discharges Dashboard")

uploaded = st.file_uploader("/content/drive/MyDrive/Dataset Scenario 2:Hospital Inpatient Discharges Dashboard/Hospital_Inpatient_Discharges__SPARCS_De-Identified___2021_20231012.csv", type=["csv"])

if uploaded:
    df = pd.read_csv(uploaded)
    df.columns = df.columns.str.strip()

    if "Length_of_Stay" in df.columns:
        df = df[df["Length_of_Stay"] >= 0]

    numeric_cols = df.select_dtypes(include=np.number).columns
    categorical_cols = df.select_dtypes(exclude=np.number).columns

    st.sidebar.header("Filters")
    diagnosis_filter = st.sidebar.multiselect("Diagnosis Code", df["Diagnosis"].unique() if "Diagnosis" in df.columns else [], default=None)
    severity_filter = st.sidebar.multiselect("Severity Level", df["Severity"].unique() if "Severity" in df.columns else [], default=None)
    payment_filter = st.sidebar.multiselect("Payment Type", df["Payment_Type"].unique() if "Payment_Type" in df.columns else [], default=None)

    temp = df.copy()
    if diagnosis_filter:
        temp = temp[temp["Diagnosis"].isin(diagnosis_filter)]
    if severity_filter:
        temp = temp[temp["Severity"].isin(severity_filter)]
    if payment_filter:
        temp = temp[temp["Payment_Type"].isin(payment_filter)]

    st.subheader("Dataset Overview")
    st.dataframe(temp.head(50))

    st.subheader("Average Hospital Stay per Diagnosis Code")
    if "Diagnosis" in temp.columns and "Length_of_Stay" in temp.columns:
        stay_chart = temp.groupby("Diagnosis")["Length_of_Stay"].mean().reset_index()
        fig1 = px.bar(stay_chart, x="Diagnosis", y="Length_of_Stay")
        st.plotly_chart(fig1, use_container_width=True)

    st.subheader("Charges by Severity Level")
    if "Severity" in temp.columns and "Total_Charges" in temp.columns:
        fig2 = px.box(temp, x="Severity", y="Total_Charges")
        st.plotly_chart(fig2, use_container_width=True)

    st.subheader("Average Length of Stay by Facility and County")
    if "Facility" in temp.columns and "County" in temp.columns and "Length_of_Stay" in temp.columns:
        pivot_table = temp.pivot_table(values="Length_of_Stay", index="Facility", columns="County", aggfunc="mean")
        fig3 = px.imshow(pivot_table, aspect="auto")
        st.plotly_chart(fig3, use_container_width=True)

    st.subheader("Patients Distribution by Payment Type")
    if "Payment_Type" in temp.columns:
        payment_counts = temp["Payment_Type"].value_counts().reset_index()
        payment_counts.columns = ["Payment_Type", "Count"]
        fig4 = px.pie(payment_counts, names="Payment_Type", values="Count")
        st.plotly_chart(fig4, use_container_width=True)

    st.subheader("Distribution of Length of Stay")
    if "Length_of_Stay" in temp.columns:
        fig5 = px.histogram(temp, x="Length_of_Stay")
        st.plotly_chart(fig5, use_container_width=True)